name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest
        container: ayberkozgur/stm32-ci:1.0
        steps:
            - uses: actions/checkout@v2
            - name: Test
              run: ci/test.sh
